services:
  - type: web
    name: memorymania-backend
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://memorymania-frontend.onrender.com

  - type: static
    name: memorymania-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: NODE_ENV
        value: production
